//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirela.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciasLaborales
    {
        public int Id { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> SYSUserID { get; set; }
    
        public virtual SYSUser SYSUser { get; set; }
    }
}
