//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirela.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SirelaDBEntities : DbContext
    {
        public SirelaDBEntities()
            : base("name=SirelaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOOKUPRole> LOOKUPRole { get; set; }
        public virtual DbSet<SYSUser> SYSUser { get; set; }
        public virtual DbSet<SYSUserProfile> SYSUserProfile { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRole { get; set; }
        public virtual DbSet<Rubros> Rubros { get; set; }
        public virtual DbSet<ReferenciasLaborales> ReferenciasLaborales { get; set; }
    }
}
